CREATE TABLE `legacy_buses` (
	`id` text PRIMARY KEY NOT NULL,
	`bus_number` text NOT NULL,
	`plate_number` text NOT NULL,
	`driver_id` text,
	`driver_name` text NOT NULL,
	`driver_phone` text NOT NULL,
	`driver_avatar` text NOT NULL,
	`capacity` integer NOT NULL,
	`current_occupancy` integer DEFAULT 0 NOT NULL,
	`current_lat` real NOT NULL,
	`current_lng` real NOT NULL,
	`speed_kmh` real DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'idle' NOT NULL,
	`fuel_level` real DEFAULT 100 NOT NULL,
	`safety_score` real DEFAULT 100 NOT NULL,
	`assigned_route_id` text,
	`next_stop_name` text NOT NULL,
	`next_stop_eta_mins` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`driver_id`) REFERENCES `legacy_users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `legacy_students` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`grade` text NOT NULL,
	`avatar` text NOT NULL,
	`school_id` text NOT NULL,
	`school_name` text NOT NULL,
	`parent_id` text,
	`parent_name` text NOT NULL,
	`parent_phone` text NOT NULL,
	`bus_id` text NOT NULL,
	`bus_number` text NOT NULL,
	`pickup_lat` real NOT NULL,
	`pickup_lng` real NOT NULL,
	`pickup_address` text NOT NULL,
	`pickup_name_ar` text NOT NULL,
	`status` text DEFAULT 'at_home' NOT NULL,
	`pickup_time_planned` text NOT NULL,
	`pickup_time_actual` text,
	`seat_number` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`parent_id`) REFERENCES `legacy_users`(`id`) ON UPDATE no action ON DELETE no action
);
